[package]
name = "dropbox"
version = "0.1.0"
authors = ["souryo <dev.souryo@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.10"
hyper-native-tls = "0"
log = "0.3"
